### ISSUE TITLE
Quando criado dois momentos do dia para o mesmo dia quem está prevalecendo é o mais antigo.

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/powerstats-api#1]
Já havia um momento cadastrado para o dia 6, eu criei um novo para o mesmo dia, o que aconteceu é que permaneceu no site o mais antigo adicionado. Para fazer o novo aparecer eu tive que desativar o antigo. Quando ativei o antigo de novo quem permaneceu foi o novo.

**Comment by adaoraul** [comment]
Só existe um momento do dia
